name: GothicJobsTabernero
main: com.loncha.gothicjobstabernero.Main
version: 1.0
commands:
   reloadtabernero:
      description: Recarga todos los archivos de configuracion del tabernero.
      usage: /reloadtabernero
   